# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/prism.xdc

# Block Designs: bd/Prism/Prism.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism || ORIG_REF_NAME==Prism} -quiet] -quiet

# IP: bd/Prism/ip/Prism_axi_vdma_0_0/Prism_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_axi_vdma_0_0 || ORIG_REF_NAME==Prism_axi_vdma_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_auto_cc_0/Prism_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_auto_cc_0 || ORIG_REF_NAME==Prism_auto_cc_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_xdma_0_axi_periph_0/Prism_xdma_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_xdma_0_axi_periph_0 || ORIG_REF_NAME==Prism_xdma_0_axi_periph_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_clk_wiz_0/Prism_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_clk_wiz_0 || ORIG_REF_NAME==Prism_clk_wiz_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_mig_7series_0_0/Prism_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_mig_7series_0_0 || ORIG_REF_NAME==Prism_mig_7series_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_v_axi4s_vid_out_0_0/Prism_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==Prism_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_v_tc_0_0/Prism_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_v_tc_0_0 || ORIG_REF_NAME==Prism_v_tc_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_axi_smc_0/Prism_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_axi_smc_0 || ORIG_REF_NAME==Prism_axi_smc_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_rst_mig_7series_0_100M_0/Prism_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==Prism_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_rgb2dvi_0_0/Prism_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_rgb2dvi_0_0 || ORIG_REF_NAME==Prism_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_util_ds_buf_0_0 || ORIG_REF_NAME==Prism_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_xdma_1_0/Prism_xdma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_xdma_1_0 || ORIG_REF_NAME==Prism_xdma_1_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_xlslice_0_0/Prism_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_xlslice_0_0 || ORIG_REF_NAME==Prism_xlslice_0_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_xlslice_1_0/Prism_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_xlslice_1_0 || ORIG_REF_NAME==Prism_xlslice_1_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_xlslice_2_0/Prism_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_xlslice_2_0 || ORIG_REF_NAME==Prism_xlslice_2_0} -quiet] -quiet

# IP: bd/Prism/ip/Prism_xlconcat_0_0/Prism_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Prism_xlconcat_0_0 || ORIG_REF_NAME==Prism_xlconcat_0_0} -quiet] -quiet

# XDC: d:/PrismGPU/PrismGPU/HardWare/Display/Display.gen/sources_1/bd/Prism/Prism_ooc.xdc
