###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Jan 21 21:57:53 2025

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       Prism_mig_7series_0_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K70T-FBG676
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR2_SDRAM->Components->MT47H64M16XX-25
## Data Width: 32
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 10 [get_ports sys_clk_i]
          
create_clock -period 5 [get_ports clk_ref_i]
          