# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/PrismGPU/PrismGPU/HardWare/Display/Display.srcs/sources_1/bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0.xci
# IP: The module: 'Prism_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PrismGPU/PrismGPU/HardWare/Display/Display.gen/sources_1/bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prism_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/PrismGPU/PrismGPU/HardWare/Display/Display.gen/sources_1/bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prism_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/PrismGPU/PrismGPU/HardWare/Display/Display.srcs/sources_1/bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0.xci
# IP: The module: 'Prism_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PrismGPU/PrismGPU/HardWare/Display/Display.gen/sources_1/bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prism_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/PrismGPU/PrismGPU/HardWare/Display/Display.gen/sources_1/bd/Prism/ip/Prism_util_ds_buf_0_0/Prism_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Prism_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
